version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "06:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(actions)"
    groups:
      github-actions-maintenance:
        patterns:
          - "*"
