#!/usr/bin/env python3
from __future__ import annotations

import json
import re
import sys
from html.parser import HTMLParser
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
APP = ROOT / "command-center"


class Collector(HTMLParser):
    def __init__(self):
        super().__init__()
        self.refs: list[tuple[str, str]] = []
        self.ids: set[str] = set()

    def handle_starttag(self, tag, attrs):
        data = dict(attrs)
        if data.get("id"):
            if data["id"] in self.ids:
                raise AssertionError(f"duplicate id: {data['id']}")
            self.ids.add(data["id"])
        for attr in ("src", "href"):
            if data.get(attr):
                self.refs.append((tag, data[attr]))


def require(condition: bool, message: str):
    if not condition:
        raise AssertionError(message)


def main() -> int:
    html = (APP / "index.html").read_text(encoding="utf-8")
    css = (APP / "assets" / "app.css").read_text(encoding="utf-8")
    command_css = (APP / "assets" / "command.css").read_text(encoding="utf-8")
    js = (APP / "assets" / "app.js").read_text(encoding="utf-8")
    workflow = (ROOT / ".github" / "workflows" / "vds-command-center-pages.yml").read_text(encoding="utf-8")

    parser = Collector()
    parser.feed(html)

    require("OPENAI_API_KEY" not in html + css + command_css + js, "OpenAI key symbol leaked to static app")
    require("api.github.com" in html and "api.github.com" in js, "private GitHub API transport missing")
    require("sessionStorage" in js, "session-only token storage invariant missing")
    require("localStorage" not in js, "GitHub token must not persist in localStorage")
    require("eval(" not in js and "new Function" not in js, "dynamic code execution forbidden")
    require("fonts.googleapis.com" not in html and "cdn.jsdelivr.net" not in html, "runtime CDN reference found")
    require("assets/vendor/chart.umd.min.js" in html, "local Chart.js reference missing")
    require("assets/command.css" in html, "command console CSS missing")
    require("connect-src 'self' https://api.github.com" in html, "CSP private API rule missing")
    require("api/v1" not in workflow or "cp -R api/v1" not in workflow, "Pages workflow must not publish private CRM JSON")
    require("test ! -d .pages/api" in workflow, "Pages security smoke test missing")

    for tag, ref in parser.refs:
        if ref.startswith(("http://", "https://", "#", "mailto:", "tel:")):
            continue
        target = (APP / ref.split("?", 1)[0].split("#", 1)[0]).resolve()
        # Runtime-vendored fonts/vendor files are intentionally generated by the Pages workflow.
        generated = any(part in ref for part in ("assets/vendor/", "assets/fonts/"))
        if not generated:
            require(target.exists(), f"missing static reference: {tag} {ref}")

    # Projection builder must clearly promise read-only canonical behavior.
    builder = (ROOT / "scripts" / "build_command_center_api.py").read_text(encoding="utf-8")
    require("writes only under api/v1" in builder.lower(), "projection read-model invariant missing")
    require("production_search_independent" in builder, "search independence health field missing")
    require("companies.json" in builder and "territory-productivity.json" in builder, "required read models missing")

    # AI command router must never directly send mail.
    router = (ROOT / "scripts" / "vds_ai_command.py").read_text(encoding="utf-8")
    require("NEVER sends mail" in router, "AI no-direct-send invariant missing")
    require("requires_existing_gates" in router, "existing gate requirement missing")
    require("VDS_REQUEST_ID" in router, "command correlation missing")

    manifest = json.loads((APP / "manifest.webmanifest").read_text(encoding="utf-8"))
    require(manifest.get("display") == "standalone", "PWA standalone mode missing")

    # Basic responsive/accessibility hooks.
    require("prefers-reduced-motion" in css, "reduced motion support missing")
    require("skip-link" in html, "skip navigation missing")
    require('aria-live="polite"' in html, "live region missing")
    require("@font-face" in css and "DM Sans Local" in css, "local font configuration missing")
    require("Material Symbols Rounded Local" in css, "local icon font configuration missing")

    print("VDS Command Center static/security QA: PASS")
    print(f"HTML ids checked: {len(parser.ids)}")
    print(f"Static references checked: {len(parser.refs)}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except AssertionError as exc:
        print(f"QA FAIL: {exc}", file=sys.stderr)
        raise SystemExit(1)
